version: "3.9"

services:
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    expose:
      - 27017
    volumes:
      - "/docker/containers/meshcentral/database:/data/db"
    networks:
      - reverse_proxy

  meshcentral:
    restart: always
    container_name: meshcentral
    depends_on:
      - mongodb
    image: typhonragewind/meshcentral:mongodb-latest
    ports:
      - 8786:443 #MeshCentral will moan and try everything not to use port 80, but you can also use it if you so desire, just change the config.json according to your needs
    environment:
      - HOSTNAME=meshcentral.laptopwiki.eu #your hostname
      - REVERSE_PROXY=nginx-proxy-manager #set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
      - REVERSE_PROXY_TLS_PORT=443 #internal https port, only change if you don't use 443 for your incoming HTTPS for some reason
      - IFRAME=false #set to true if you wish to enable iframe support
      - ALLOW_NEW_ACCOUNTS=false #set to false if you want disable self-service creation of new accounts besides the first (admin)
      - WEBRTC=false #set to true to enable WebRTC - per documentation it is not offically released with meshcentral, but is solid enough to work with. Use with caution
      - NODE_ENV=production
      - TZ=Asia/Kuching
    volumes:
      - data:/opt/meshcentral/meshcentral-data
      - files:/opt/meshcentral/meshcentral-files
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true

volumes:
  data:
  files:
